######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 15 18:07:07 2009
######################################################################

TEMPLATE = lib
TARGET = qijtextile
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QijTextile.h
SOURCES += QijTextile.cc
